apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-service-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_USER/YOUR_REPO'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: my-lab-project
  syncPolicy:
    automated: {}